# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='IP_addr',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
