# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0004_auto_20160212_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publisher',
        ),
    ]
