# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0005_auto_20160223_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FilePathField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Forum.Video'),
        ),
    ]
