# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0006_auto_20160212_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
