# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0008_auto_20160223_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FilePathField(null=True)),
                ('video', models.FilePathField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='article',
            name='video',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='article',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Forum.Media'),
        ),
    ]
